[package]
name = "npyz-viewer-rocky8"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Rocky Linux 8 compatible Tauri 1 shell for npyz-viewer"
autobins = false

[build-dependencies]
tauri-build = "=1.5.6"

[dependencies]
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
serde = { version = "1", features = ["derive"] }
javascriptcore-rs-sys = { version = "0.4.0", optional = true, features = ["dox"] }
soup2-sys = { version = "0.2.0", optional = true, features = ["dox"] }
tauri = { version = "=1.8.3", default-features = false, features = ["wry", "dialog-open"] }
webkit2gtk-sys = { version = "0.18.0", optional = true, features = ["dox"] }
zip = { version = "2.4.2", default-features = false, features = ["deflate-flate2", "flate2"] }

[dev-dependencies]
ndarray = "0.16.1"
ndarray-npy = "0.9.1"

[features]
dox = ["tauri/dox", "dep:javascriptcore-rs-sys", "dep:soup2-sys", "dep:webkit2gtk-sys"]

[[bin]]
name = "npyz-viewer"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"
